### ISSUE TITLE
Fix Null Pointer Exception in Seller "Accept Order"

### ISSUE THREAD

**Issue by VivianLiu2357** [CSC207-2022F-UofT/course-project-group-134#98]
When logging in as a seller and there are no active orders for the seller's residence, clicking on ""Accept Order"" throws a null pointer exception in the console. You may add a check or catch the exception.

**Comment by adityabandekar** [comment]
Completed here: https://github.com/CSC207-2022F-UofT/course-project-group-134/pull/109
